-- AlterTable
ALTER TABLE "public"."Property" ADD COLUMN     "coverIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "imageKeys" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "images" SET DEFAULT ARRAY[]::TEXT[];
